import React, { Component } from 'react';
//import '../styles/tos.css';

class Tos extends Component {

  render() {
    const baseUrl = sessionStorage.getItem('baseUrl');
    return (
      <React.Fragment>
        <div className="container">
          <div style={{ maxWidth: '600px', margin: '20px auto', textAlign:'justify'}}>
			<h1>Terms of Service</h1>
            <p>1. Introduction &amp; Legal Agreement</p>
            <p>These Terms of Use apply to the Xtendly LLC online and mobile sites on which we have posted these Terms of Use (collectively, the “Sites”). The Sites are operated by Xtendly LLC along with our affiliates and subsidiary sites including prosperna.com (collectively, “we,” “our,” “us”). You agree that by clicking “Start a Demo”, “Book a Demo, “Sign Up”, “Get Started”, “Buy Now”, “Upgrade Now” or similar, registering, accessing or using our services (including our Paid Services (defined below), or any content or information provided as part of these services, collectively, “Services”), you are entering into a legally binding agreement (even if you are using our Services on behalf of a company).</p>
            <p>Important: Prosperna.com is built by the friendly folks at Xtendly LLC, so when you receive a charge on your credit card for your prosperna.com subscription please note that this will be from Xtendly LLC.</p>
            <p>2. Member Account and Member Website</p>
            <p>If anyone other than yourself accesses your Member Account, and/or any of your Member Account settings, and/or your Member website (“Member Website”) they may perform any actions available to you, make changes to your Member Account, Member Account settings, or Member Website and accept any legal terms available therein, make various representations and warranties and all such activities will be deemed to have occurred on your behalf and in your name.</p>
            <p>Therefore, we strongly encourage you to keep the log-in credentials of your Member Account confidential, and allow such access only to people you trust – as you will be solely and fully be responsible for all activities that occur under your Member Account (including for any representations, warranties and undertakings made therein), whether or not specifically authorized by you, and for any damages, expenses or losses that may result from such activities.</p>
            <p>You must provide accurate and complete information when registering your Member Account and using the Services, to which you are the sole and exclusive rights holder. You are required to provide your own (or your company’s) contact and billing details, including your valid e-mail address, as we may use it to identify and determine the actual and true owner of the Member Account and/or Member Content (as defined below) submitted to us.</p>
            <p>We reserve the right to determine and/or grant ownership to a Member Account based on our reasonable judgment, whether or not an independent investigation has been conducted by us. However, if we cannot make such determination (as we may deem in our sole discretion), we reserve the right to avoid doing so, without liability to you or to any other party. Among others, we may consider the principles set forth below.</p>
            <p>Please carefully review these principles and consider adapting your practices accordingly, to ensure that what you believe to be “your” Member Account and/or Member Website remains as such:</p>
            <p>The owner of a Member Account, Member Website and/or Member Content created and/or uploaded to the Services, may be considered to be the person or entity who has access to the e-mail address then listed in our records for such Member Account under which such Member Website or Member Content has been created.</p>
            <p>If any Paid Services (as defined below) were procured via the Member Account, the owner of such Member Account, or any Member Website and/or Member Content created thereunder, may be considered to be the person or entity whose billing details were used to purchase such Paid Services. Notwithstanding the foregoing, if a Member Website was connected to an external domain name (either imported or purchased as part of certain Paid Services, as defined below), and such domain’s registration information is publicly available via the WHOIS database provided on the www.whois.net website, the owner of such Member Website may be determined to be the person or entity registered as the owner of such domain thereunder. In the event that both an individual and an organization are registered as the owner of such domain, we will consider the organization as the actual owner of the domain, and therefore as the owner of the Member Website connected to such domain. All activities that occur under your Member Account or Member Website are your responsibility.</p>
            <p>3. Member Account Information</p>
            <p>The account information you provide us must be your own (or your company’s), and be accurate and complete. We will determine the ownership of all Member Accounts. You represent and warrant that:</p>
            <p>A. You are at least eighteen (18) years of age, or of the legal age of majority in your jurisdiction, and possess the legal authority, right and freedom to enter into this Agreement and to form a binding agreement, for yourself or on behalf of the person or entity committed by you to the Agreement;<br />
            B. You are not a resident of (or will use the Services in) a country that the U.S. government has embargoed for use of the Services, nor are you named on the U.S. Treasury Department’s list of Specially Designated Nationals or any other applicable trade sanctioning regulations;<br />
            C. Your country of residence and/or your company’s country of incorporation is the same as the country specified in the contact and/or billing address you provide us; you understand that we do not provide any legal advice or any recommendation with respect to any laws or requirements applicable to your use or any of your end users, or your compliance therewith;<br />
            D. And specifically regarding your Member Content: you own all rights in and to any content uploaded by you (“Member Content”), including any designs, images, animations, videos, audio files, fonts, logos, illustrations, compositions, artworks, interfaces, text, literary works and any other materials (“Content”), or otherwise have (and will continue to have) the full power, title, licenses, consents and authority, in and to the Member Content, as necessary to legally use, publish, transfer or license any and all rights and interests in and to such Member Content; the Member Content is (and will continue to be) true, current, accurate, non-infringing upon any third party rights, and in no way unlawful for you to possess, post, transmit or display in the country in which you or your Member Website’s visitors and users reside, or for us and/or your visitors and users to use or possess in connection with the Services; you have obtained all consents and permissions required under all applicable laws, regarding the posting, transmission and publication of any personal information and/or image or likeness of any person, entity or property which is part of the Member Content, and you will adhere to all laws applicable thereto.</p>
            <p>4. Your Obligations:</p>
            <p>In order to participate on the Sites and access the Services, you agree that you will:<br />
            A. Fully comply with all applicable laws and any other contractual terms which govern your use of the Services (and any related interaction or transaction), including those specific laws applicable to you or your users and visitors in any of your geographical locations;<br />
            be solely responsible and liable with respect to any of the uses of the Services which occur under your Member Account and/or Member Website(s), and for any of your Member Content (including for any consequences of using or publishing such Member Content on or with respect to the Services);<br />
            B. Regularly and independently save and backup any of your Member Content and the information that is being processed by you regarding your Member Website, including with respect to your visitors and users, and any applications and/or Third Party Services used by you;<br />
            C. Receive from time to time promotional messages and materials from us or our partners, by mail, social media, e-mail or any other contact form you may provide us with (including your phone number for calls or text messages). If you wish not to receive such promotional materials or notices, please just notify us at any time; allow us to use in perpetuity, worldwide and free of charge, any version of your Member Website (or any part thereof) for any of our marketing and promotional activities, online and/or offline, and modify it as reasonably required for such purposes, and you waive any claims against us or anyone on our behalf relating to any past, present or future moral rights, artists’ rights, or any other similar rights worldwide that you may have in or to your Member Website with respect to such limited permitted uses;<br />
            D. Further, you acknowledge and agree that we, in our sole discretion, shall determine the means, manner, and method for performing the Services, including those regarding the hosting, transmission, publication and/or display of any Member Websites and/or Content (including the inclusion and presentation of any advertisements or other commercial content with respect thereto).</p>
            <p>In addition, you undertake and agree NOT to:</p>
            <p>A. Copy, modify, create derivative works of, download, adapt, reverse engineer, emulate, migrate to another service, translate, compile, decompile or disassemble any of the Sites, the Services (or any part thereof), any Content offered by us or Third Party Services for use and display within Member Websites (“Licensed Content”) and/or any part thereof in any way, or publicly display, perform, transmit or distribute any of the foregoing without our prior written and specific consent and/or as expressly permitted under this Agreement; submit, transmit or display any Member Content, or use Licensed Content in a context, which may be deemed as defamatory, libelous, obscene, harassing, threatening, incendiary, abusive, racist, offensive, deceptive or fraudulent, encouraging criminal or harmful conduct, or which otherwise violates the rights of us or any third party (including any intellectual property rights, privacy rights, contractual or fiduciary rights), or otherwise shows any person, entity or brand in a bad or disparaging light, without their prior explicit approval; publish and/or make any use of the Services or Licensed Content on any website, media, network or system other than those provided by us, and/or frame, “deep link”, “page scrape”, mirror and/or create a browser or border environment around any of the Services, Licensed Content and/or Member Website (or any part thereof), except as expressly permitted by us, in advance and in writing; use any “robot”, “spider” or other automatic device, program, script, algorithm, or methodology, or any similar or equivalent manual process, to access, acquire, copy, or monitor any portion of the Services (or its data), or in any way reproduce or circumvent the navigational structure or presentation of any of the Services to obtain or attempt to obtain any materials, documents, services or information through any means not purposely made available through the Services;<br />
            B. Act in a manner which might be perceived as damaging to our reputation and goodwill or which may bring us into disrepute or harm;<br />
            purchase search engine or other pay per click keywords (such as Google AdWords), or domain names that use our name or our Marks and/or variations and misspellings thereof; impersonate any person or entity or provide false information on the Services and/or Member Website, whether directly or indirectly, or otherwise perform any manipulation in order to disguise your identity or the origin of any message or transmittal you send to us and/or any of our other Visitors or Members; falsely state or otherwise misrepresent your affiliation with any person or entity, or falsely express or imply that we or any third party endorses you, your Member Website, your business, your Member Products, or any statement you make;<br />
            C. Reverse look-up, trace, or seek to trace another Member of Services, or otherwise interfere with or violate any other Member’s right to privacy or other rights, or harvest or collect personally identifiable information about visitors or users of the Services and/or Member Website without their express and informed consent; disable, circumvent, bypass or otherwise avoid any measures used to prevent or restrict access to the Services, Member Website, the account of another Member(s), or any other systems or networks connected to the Services, by hacking, password mining, or other illegitimate or prohibited means; probe, scan, or test the vulnerability of the Services or any network connected to the Services;<br />
            D. Upload to the Services and/or Member Website or otherwise use them to design, develop, distribute and/or otherwise transmit or execute, any virus, worm, Trojan Horse, time bomb, web bug, spyware, malware, or any other computer code, file, or program that may or is intended to damage or hijack the operation of any hardware, software, or telecommunications equipment, or any other actually or potentially harmful, disruptive, or invasive code or component; take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Services or our systems or networks connected to the Services, or otherwise interfere with or disrupt the operation of any of the Services, or the servers or networks that host them or make them available, or disobey any requirements, procedures, policies, or regulations of such servers or networks;<br />
            E. Use any of the Services and/or Member Website in connection with any form of spam, unsolicited mail, fraud, scam, phishing, “chain letters”, “pyramid schemes” or similar conduct, or otherwise engage in unethical marketing or advertising; sell, license, or exploit for any commercial purposes any use of or access to the Licensed Content and/or Services, except as expressly permitted by this Agreement; remove or alter any copyright notices, watermarks, restrictions and signs indicating proprietary rights of any of our licensors, including copyright mark [©] or trademarks [® or ™] contained in or accompanying the Services and/or Licensed Content; or violate, attempt to violate, or otherwise fail to comply with this Agreement or any laws or requirements applicable to your use of the Services.</p>
            <p>You acknowledge and agree that your failure to abide by any of the foregoing or any misrepresentation made by you herein may result in the immediate termination of your Member Account and/or any Services provided to you, with or without further notice to you, and without any refund of amounts paid on account of any such Services.</p>
            <p>5. Content and Ownership</p>
            <p>As between us and you, you shall own all intellectual property pertaining to your Member Content, including to any designs, images, animations, videos, audio files, fonts, logos, illustrations, compositions, artworks, interfaces, text, literary works and any other materials created by you. You hereby grant us a royalty-free, perpetual, irrevocable, non-exclusive, transferable and sublicensable right and license to use your Member Content (in whole or in part) worldwide in order to provide you with the Services, and as further specified under this Agreement.</p>
            <p>All rights, title and interest in and to the Services, including any and all copyrightable materials or any other content thereof which is or may be subject to any intellectual property rights under any applicable law (including any artwork, graphics, images, website templates and widgets, literary work, source and object code, computer code (including html), applications, audio, music, video and other media, designs, animations, interfaces, the “look and feel” of the Services, methods, products, algorithms, data, interactive features and objects, advertising and acquisition tools and methods, inventions, trade secrets, logos, domains, customized URLs, trademarks, service marks, trade names and other proprietary identifiers, whether or not registered and/or capable of being registered (collectively, “Intellectual Property”), and any derivations thereof, are owned by and/or licensed to us.</p>
            <p>Subject to your full compliance with this Agreement and timely payment of all applicable Fees, we hereby grant you, upon creating your Member Account and for as long as we wish to provide you with the Services, a non-exclusive, non-transferable, non-sublicensable, fully revocable, limited license to use the Services and Licensed Content, for the purpose of accessing and using the Services and generating and displaying your Member Website, solely as expressly permitted under the terms of this Agreement, and solely within the Services.</p>
            <p>The terms of the Agreement do not convey any right or interest in or to our Intellectual Property (or any part thereof), except only for the limited license expressly granted above. Nothing in the Agreement constitutes an assignment or waiver of our Intellectual Property rights under any law.</p>
            <p>6. Suggestions, Comments and Feedback</p>
            <p>If you provide us with any suggestions, comments or other feedback relating to the Services (whether existing, suggested or contemplated), which is or may be subject to any Intellectual Property rights (“Feedback”), such Feedback shall be exclusively owned by us. By providing such Feedback to us, you (1) represent and warrant that such Feedback is accurate, complete, and does not infringe on any third party rights; (2) irrevocably assign to us any right, title and interest you may have in such Feedback, (3) explicitly and irrevocably waive any and all claims relating to any past, present or future moral rights, artists’ rights, or any other similar rights worldwide in or to such Feedback.</p>
            <p>7. Privacy Policy</p>
            <p>Certain parts of the Services (including certain Third Party Services available therein, as further explained below) require or involve the submission, collection and/or use of certain personally identifying or identifiable information. In particular and as a part of accessing or using the Services, we and such Third Party Services may collect, access and use certain data pertaining to Members and your visitors and users, including the activities or navigation undertaken by Members and such visitors and users through the Services and/or Member Websites. We encourage you to read our Privacy Policy [https://www.prosperna.com/privacy] and each such Third Party Services’ relevant policies on a regular basis, for a description of such data collection and use practices.</p>
            <p>8. Payment</p>
            <p>The use of certain Services may be subject to payment of particular fees, as determined by us in our sole discretion (“Paid Services” and “Fee(s)”, respectively). We will provide notice of such Fees then in effect in relation to such Paid Services. If you wish to receive or use such Paid Services, you are required to pay all applicable Fees in advance.</p>
            <p>We reserve the right to change our Fees at any time, upon notice to you if such change may affect your existing subscriptions. If you received a discount or other promotional offer, we shall have the right to automatically and without notice renew your subscription to such Service(s) at the full applicable Fee.</p>
            <p>All Fees shall be deemed to be in U.S. Dollars or Philippine Pesos, except as specifically stated otherwise in writing by us. To the extent permitted by law (and unless specified otherwise by us in writing), all Fees are exclusive of all taxes (including value added tax, sales tax, goods and services tax, VAT, etc.), levies or duties imposed by taxing authorities (“Taxes”), and you shall be responsible for payment of all applicable Taxes relating to your use of the Services, or to any payments or purchases made by you. If we are obligated to collect or pay Taxes for the Fees payable by you, and whether or not such Taxes were added and collected from you for previous transactions, such Taxes may be added to the payment of any outstanding Fees and will be reflected in the Invoice for such transaction.</p>
            <p>As part of registering or submitting information to receive Paid Services, you also authorize us (either directly or through our affiliates, subsidiaries or other third parties) to request and collect payment (or otherwise charge, refund or take any other billing actions) from our payment provider or your designated banking account, and to make any inquiries we or our subsidiaries or affiliates may consider necessary to validate your designated payment account or financial information, in order to ensure prompt payment, including for the purpose of receiving updated payment details from your payment, credit card or banking account provider (e.g., updated expiry date or card number as may be provided to us by your credit card company). As noted above, prosperna.com is built by Xtendly LLC, so when you submit your payment to BDO for Over-the-Counter (OTC) payment, it will be addressed to Xtendly Philippines Inc., or when you receive an online charge on your credit card, PayPal or Coins.ph account for your prosperna.com subscription, it will show as either Xtendly LLC or Prosperna.</p>
            <p>We and/or our subsidiary or affiliated companies will issue an invoice or credit memo for any payment of Fees or refund made to or by us (“Invoice”). Each Invoice will be issued in electronic form and based on the country stated in your billing address, and will be made available to you via your Member Account and/or by e-mail. For the purpose of issuing the Invoice, you may be required to furnish certain personal information in order to comply with local laws. Please note that the Invoice presented in your Member Account may be inadequate with your local law requirements, and in such case may be used for pro forma purposes only.</p>
            <p>In order to ensure that you do not experience any interruption or loss of services due to the lapse of any particular subscription period, the Services operate with automatic renewal, on a recurring-fees basis (except where explicitly stated otherwise by us in writing). Accordingly, where applicable, we will attempt to automatically renew the applicable Service(s) for a renewal period equal in time to the original subscription period for such Service, and automatically charge you the applicable Fees using the payment method you have on file with us. All Prosperna CRM plans have a minimum one (1) month contract term. At the end of each term, this Agreement shall automatically renew for a subsequent one (1) month unless terminated by either party in writing at least thirty (30) days prior to the expiration of the then-current term.</p>
            <p>For example, if the original subscription period for a Service is one month, each of the renewal periods (where applicable) will be for one month. Therefore, unless you cancel the applicable Service(s), we will automatically renew such Service when it comes up for renewal, and charge you the applicable recurring Fees. In order to avoid any interruptions or loss of services due to failure to process renewal charges prior to the expiration of the subscription period then in effect, we reserve our right (but shall not be obligated) to charge for the upcoming renewal period up to two (2) weeks before such renewal period actually commences. In the event of failure to collect the Fees owed by you, we may in our sole discretion (but shall not be obligated to) retry to collect on a later time, and/or suspend or cancel your Member Account, without further notice.</p>
            <p>9. Cancelling Paid Services</p>
            <p>Notwithstanding anything to the contrary in the foregoing, you are and shall be solely responsible to verify and ensure the successful renewal of the Services you use (whether or not such Services are subject to automatic subscription renewals).</p>
            <p>Accordingly, you shall be solely responsible with respect to any discontinuation of any Services previously purchased by you, including due to a cancellation, failure to charge the applicable recurring Fees, or due to any Services not being subject to automatic subscription renewals. You acknowledge and agree that you shall not have any claims against us in relation to the discontinuation of any Services or Third Party Services, for whatever reason. Any services not provided during the term of the subscription and contract period, due to Client’s failure to perform it’s stated responsibilities or use their Member Account, including logging into their Member Account, shall be deemed delivered without any liability or obligation of Prosperna.</p>
            <p>Please note: Certain services purchased on or through the Services may be non-refundable. These include Third Party Services such as domains, business tools and applications. The terms of each purchased service or application are indicated on the applicable Site and/or as part of or during the process of purchasing such services or applications. It is your obligation to verify your ability to cancel a service prior to purchasing it. We will not refund any amounts paid for non-refundable Paid Services, applications or Third Party Services. In addition, should you select a long-term (more than a one moth) prepaid subscription option, zero refund will be granted once you accept this order.</p>
            <p>10. Chargebacks</p>
            <p>If, at any time, you contact your bank or credit card company and decline, chargeback or otherwise reject the charge of any payable Fees (“Chargeback”), this act will be considered a breach of your payment obligations hereunder, and your use of the Services may be automatically terminated.</p>
            <p>In the event a Chargeback is performed, your Member Account may be blocked without the option to re-purchase or re-use it, and any data contained in such Member Account, including any domains, applications and Third Party Services may be subject to cancellation and Capacity Loss (as defined in below).</p>
            <p>Your use of the Services will not resume until you re-subscribe for any such Services, and pay any applicable Fees in full, including any fees and expenses incurred by us and/or any Third Party Services for each Chargeback received (including Fees for Services provided prior to the Chargeback, handling and processing charges and fees incurred by the payment processor).</p>
            <p>If you have any questions or concerns regarding a payment made to us, we encourage you to first contact our Customer Support team at support@prosperna.com before filing a Chargeback or reversal of payment, in order to prevent the Services from being cancelled and your Member Account being blocked, and to avoid the filing of an unwarranted or erroneous Chargeback, which may result in your being liable for its applicable Fees, in addition to re-payment of all the Fees applicable to the Services purchased (and charged-back) by you.</p>
            <p>We reserve our right to dispute any Chargeback received, including by providing the relevant credit card company or financial institution with any information and documentation proving that the Member responsible for such Chargeback did in fact authorize the transaction and make use of the services rendered thereafter.</p>
            <p>11. Late Payment and Cancellation</p>
            <p>You may discontinue to use and request to cancel your Member Account and/or any Services at any time, in accordance with the instructions available on the applicable Site(s), and may be subject to a cancellation charge equal to one month’s fee for the applicable Service. The effective date and time for such cancellation shall be the date and time on which you have completed the cancellation process on the applicable Site(s).</p>
            <p>Notwithstanding anything to the contrary in the foregoing, with respect to automatically-renewed subscriptions to Paid Services, such subscription will be discontinued only upon the expiration of the respective period for which you have already made payment. Please note that as the cancellation process may take a few days, in order to avoid the next automatic renewal and respective charge the cancellation request should be made at least fourteen (14) days prior to the expiration of the then-current service period.</p>
            <p>If your payment is unsuccessful within five working days, we will contact you to resolve the situation. If after seven working days we fail to make contact with you, then we reserve the right to cancel your service and charge a cancellation fee accordingly.</p>
            <p>Failure to comply with any of the terms set forth under this Agreement and/or to pay any due Fee shall entitle us to suspend (until full payment is made) or cancel your Member Account and Member Website (or certain features thereof), as well as the provision of any related Services (e.g., Paid Services) or Third Party Services to you.</p>
            <p>12. Loss of Data, Content and Capacity Upon Cancellation</p>
            <p>If your Member Account or any Services or Third Party Services related to your Member Account are cancelled (whether at your request or at our discretion), it may cause or result in the loss of certain content, features, or capacity of your Member Account, including any Member Content, visitor or user data or other usage data retained therein, and including any domain name reservation or registration that was included in such Services (“Capacity Loss”). We shall not be liable in any way for such Capacity Loss, or for saving a backup of your Member Account, Member Content or visitor or user data. Please also note that additional Fees may apply to re-activation of a Member Account and/or any Services following their cancellation, as determined by us in our sole discretion.</p>
            <p>13. Third Party Services</p>
            <p>The Services may enable you to engage and procure certain third party services and tools for enhancing your Member Website and your overall user experience, including domain registrars from which you may purchase a domain name for your Member Website, third party applications and widgets offered via the Site(s), third party Licensed Content, media distribution services, third party designers who may assist you with your Member Website, etc. (collectively, “Third Party Services”).</p>
            <p>You acknowledge and agree that regardless of the manner in which such Third Party Services may be offered to you (bundled with certain Services, offered separately by us or persons certified or authorized by us, or otherwise offered anywhere on the Services), we merely act as an intermediary platform between you and such Third Party Services, and do not in any way endorse any such Third Party Services, or shall be in any way responsible or liable with respect thereto. We will not be a party to, or in any way be responsible for monitoring, any interaction or transaction between you and any Third party Services</p>
            <p>Any and all use of such Third Party Services shall be done solely at your own risk and responsibility, and may be subject to such legal terms which govern such Third Party Services, which you are encouraged to review before engaging with them.</p>
            <p>Any and all use of such Third Party Services shall be done solely at your own risk and responsibility, and may be subject to such legal terms which govern such Third Party Services, which you are encouraged to review before engaging with them.</p>
            <p>14. Copyrights and DMCA</p>
            <p>We respect the intellectual property rights of others. We act in accordance with our interpretation of the Digital Millennium Copyright Act (“DMCA”). If you believe that your work has been copied or was otherwise used in a way that constitutes copyright infringement, you may notify us of such infringement by providing the following information in writing to our designated Copyright Agent: (1) the contact details of the person authorized to act on behalf of the owner of the copyright; (2) a description of the copyrighted work that you claim has been infringed; (3) a description of the material that you claim to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information sufficient to permit us to locate the material (including URL address); (4) a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (5) a statement that the information in the notification is accurate and, under penalty of perjury, that you are the copyright owner or are authorized to act on behalf of the owner of a copyright that is allegedly infringed.</p>
            <p>Our Copyright Agent can be reached at the following address:</p>
            <p>Attn: Copyright Agent</p>
            <p>Telephone Number: <span id="gc-number-1" class="gc-cs-link" title="Call with Google Voice">844-983-6359 or +63917-659-1948</span></p>
            <p>E-mail: support@prosperna.com</p>
            <p>In the event that we receive notice regarding a copyright infringement related to your Member Account or Member Website, we may cancel your Member Account, take your Member Website down or remove any Content in our sole discretion, with or without prior notice to you. In such case, you may file a proper counter-notice in accordance with Section 512 of the DMCA, in which you must include: (1) your full name, address, phone number and physical or electronic signature; (2) identification of the material and its location before removal; (3) a statement under penalty of perjury that the material was removed by mistake or misidentification; (4) your consent to an appropriate judicial body; and (5) any other information required under the relevant provisions of the DMCA. Any notices filed pursuant to this Section may be deemed accepted, applicable and compliant with the DMCA, or not, at our sole reasonable discretion. We reserve the right to notify the person or entity providing the infringement notice of such counter-notice and provide any details included therein.</p>
            <p>When using the Services, you may be exposed to Member Websites, Member Content or Third Party Services from a variety of sources, which may be inaccurate, objectionable or illegal. You hereby waive any legal or equitable rights or remedies you have or may have against us with respect thereto. If you believe a Member or any Third Party Services acted inappropriately or otherwise misused any of the Services, please immediately report such Member and/or Third Party Service to us via our contact information below. You agree that your report shall not impose any responsibility or liability upon us, and that we may consider such report and act upon it, refrain from taking any such action or require additional information or documents before doing so, at our sole discretion.</p>
            <p>15. DISCLAIMER OF WARRANTIES</p>
            <p>We provide the Sites and the Services on an “As Is”, “with all faults” and “As Available” basis, without any warranties of any kind, including any implied warranties or conditions of merchantability, fitness for a particular purpose, workmanlike effort, non-infringement, or any other warranty, all to the fullest extent permitted by law. We specifically do not represent or warrant that the Sites or Services (or any part, feature or Content thereof) are complete, accurate, of any certain quality, reliable or secure in any way, suitable for or compatible with any of your (or your visitors or users) contemplated activities, devices, operating systems, browsers, software or tools (or that they will remain as such at any time), or comply with any laws applicable to you or your visitors or users (including in any jurisdiction in which you operate), or that their operation will be free of any viruses, bugs or other harmful components or program limitations. Moreover, we do not endorse any entity, product or service (including any Third Party Services) mentioned on or made available via the Services, so please be sure to verify those before using or otherwise engaging them.</p>
            <p>We may, at our sole discretion (however we shall have no obligation to do so), screen, monitor and/or edit any Member Website and/or Member Content, at any time and for any reason, with or without notice.</p>
            <p>Notwithstanding anything to the contrary in the foregoing, in no circumstances may we be considered as a “publisher” of any Member Content, and we do not in any way endorse any Member Content or assume any liability for any Member Content uploaded, posted, published and/or made available by any Member or any other party on and/or through the Services, for any use by any party, or for any loss, deletion or damage thereto or thereof or any loss, damage, cost or expense that you or others may suffer or incur as a result of or in connection with publishing, accessing and/or relying on any Member Content. Furthermore, we shall not be liable for any mistakes, defamation, libel, falsehoods, obscenity, pornography, incitement and/or any other unlawful and/or infringing Member Content you or any other party may encounter.</p>
            <p>You acknowledge that there are risks in using the Services and/or connecting and/or dealing with any Third Party Services through or in connection with Services, and that we cannot and do not guarantee any specific outcomes from such use and/or interactions, and you hereby assume all such risks, liabilities and/or harm of any kind arising in connection with and/or resulting from such interactions. Such risks may include, among others, misrepresentation of information about and/or by Third Party Services and/or Licensed Content, breach of warranty and/or contract, violation of rights, and any consequent claims.</p>
            <p>We do not recommend the use of the Services for hosting of personal content and shall not bear any security or integrity obligations or risks regarding breach or damage to any such content.</p>
            <p>To the fullest extent permitted by law in each applicable jurisdiction, we, our officers, directors, shareholders, employees, affiliates and/or agents shall not be liable to you for any direct, indirect, incidental, special, punitive, exemplary or consequential damages whatsoever, including any damages resulting from (1) errors, mistakes, or inaccuracies of or in any content; (2) any personal injury or property damage related to your use of the Services; (3) any unauthorized access to or use of our servers and/or any personal information and/or other information stored therein; (4) any interruption or cessation of transmission to or from the Services; (5) the use or display of any Content or Member Content posted, emailed, transmitted, or otherwise made available via the Services; and/or (6) events beyond our reasonable control, including any internet failures, equipment failures, electrical power failures, strikes, labor disputes, riots, insurrections, civil disturbances, shortages of labor or materials, fires, floods, storms, earthquakes, explosions, acts of God, war, terrorism, intergalactic struggles, governmental actions, orders of courts, agencies or tribunals or non-performance of third parties.</p>
            <p>You acknowledge and agree that these limitations of liability are agreed allocations of risk constituting in part the consideration for our services to you, and such limitations will apply even if we gave been advised of the possibility of such liabilities.</p>
            <p>16. LIMITATION OF LIABILITY</p>
            <p>You agree to defend, indemnify and hold harmless us, our officers, directors, shareholders, employees, affiliates and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs, debt and expenses (including attorneys’ fees) arising from: (1) your violation of any term of this Agreement or any other terms applicable to your use of or access to the Site(s) or Services; (2) your violation of any third party right, including any copyright, property, or privacy right, resulting from your Member Website or Member Content and/or your use of the Services; and/or (3) any other type of claim that your Member Website and/or Member Content caused damage to a third party.</p>
            <p>17. INDEMNITY</p>
            <p>You agree to defend, indemnify and hold harmless us, our officers, directors, shareholders, employees, affiliates and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs, debt and expenses (including attorneys’ fees) arising from: (1) your violation of any term of this Agreement or any other terms applicable to your use of or access to the Site(s) or Services; (2) your violation of any third party right, including any copyright, property, or privacy right, resulting from your Member Website or Member Content and/or your use of the Services; and/or (3) any other type of claim that your Member Website and/or Member Content caused damage to a third party.</p>
            <p>18. General</p>
            <p>Changes and Updates:<br />
            We may change, suspend or terminate any of the Services (or any features thereof, or prices applicable thereto), and/or change any of the terms of the Agreement – at any time and in any manner. Such changes may become effective upon notice to you (and in any event, not in a retroactive manner â except as required otherwise by law). If any such changes involve the payment of additional Fees, we will provide you with a notice of such Fees prior to enabling such specific changes. If you fail or refuse to pay such Fees, we may (at our sole discretion) cancel your Member Account (as further explained above), continue to support your then-current Services without enabling such changes, or provide you with alternative Services.</p>
            <p>Governing Law<br />
            This Agreement, the rights and remedies provided hereunder, and any and all claims and disputes related hereto and/or to the Services, their interpretation, or the breach, termination or validity thereof, the relationships which result from or pursuant to this Agreement, or any related transaction or purchase, shall be governed by, construed under and enforced in all respects solely and exclusively in accordance with the internal substantive laws of the State of California, without respect to its conflict of laws principles</p>
            <p>Jurisdiction:<br />
            Any and all claims and disputes under this Agreement shall be brought in, and you hereby consent to them being decided exclusively by, a court of competent jurisdiction located in Contra Costa County, California. The application of the United Nations Convention of Contracts for the International Sale of Goods is hereby expressly excluded.</p>
            <p>Notices<br />
            We may provide you with notices in any of the following methods: (1) via the Services, including by a banner or pop-up within the applicable Site(s), Member Account or elsewhere; (2) by e-mail, sent to the e-mail address you provided us; and/or (3) through social media, or any other means, including any phone number or physical address you provided us. our notice to you will be deemed received and effective within twenty four (24) hours after it was published or sent through any of the foregoing methods, unless otherwise indicated in the notice.</p>
            <p>Headings:<br />
            Any heading, caption or section title contained herein, is provided only for convenience, and in no way defines or explains any section or provision hereof, or legally binds any of us in any way.</p>
            <p>Choice of Language:<br />
            The terms of this Agreement were written in English. If a translated (non-English) version of this Agreement conflicts in any way with their English version, the provisions of the English version shall prevail.</p>
            <p>Relationship<br />
            This Agreement, your access to the Site(s), and your use of the Services, do not, and shall not be construed to create any partnership, joint venture, employer-employee, agency, or franchisor-franchisee relationship between us and you.</p>
            <p>Entire Agreement:<br />
            This Agreement and any other legal or fee notices provided to you by us, shall constitute the entire agreement between you and us concerning the subject matter hereof or thereof, and supersede any and all prior or contemporaneous agreements, understandings, promises, conditions, negotiations, covenants or representations, whether written or oral, between us and you, including those made by or between any of our respective representatives, with respect to any of the Services. You further agree that you are not relying upon any promise, inducement, representation, statement, disclosure or duty of disclosure of us in entering into any of the terms of the Agreement.</p>
            <p>Assignment:<br />
            We may assign our rights and/or obligations hereunder and/or transfer ownership rights and title in the Services and/or Licensed Content to a third party without your consent or prior notice to you. You may not assign or transfer any of your rights and obligations hereunder without the prior written consent of us. Any attempted or actual assignment thereof without our prior explicit and written consent will be null and void. In any event, an assignment or transfer pursuant to this Section shall not in itself grant either us or you the right to cancel any Services or Third Party Services then in effect.</p>
            <p>Severability; No Waiver:<br />
            If any provision of the Agreement is deemed by a court of competent jurisdiction to be invalid, unlawful, void, or for any reason unenforceable, then such provision shall be deemed severable and will not affect the validity and enforceability of the remaining provisions. No Waiver of any breach or default of any of the terms of the Agreement shall be deemed to be a waiver of any preceding or subsequent breach or default.</p>
            <p>19. Contact Us</p>
            <p>To get in touch with our Customer Service – please us by e-mail at support@prosperna.com or by phone at <span id="gc-number-2" class="gc-cs-link" title="Call with Google Voice">844-983-6359</span> or +63917-659-1948.</p>
          </div>
        </div>
      </React.Fragment>
    );
  }
}


export default Tos;
